---
keys:
  # Users
  - &anthony age12t69fa3kqmnxdx4sca7ecv6lfu3wrfwm95zuuhujcfk3ukcn8dzsk40u6x
  # Hosts
  - &bkp1 age1uvm732gdzuq2v2m97tw5gxerztw6ad3452xrpq5y9ggvg62x7fqse4pzly
  - &master-04 age1sqmpaf3u78yg6k3t5gjzx27el7rzd2lz0emyx4nls0zvpxr6fg2qkc3a6l
  - &e39 age1a4uumamqg8248ntjjl088ppq7m75p6zyhu5r8yyaqjvvk5yjpuksqspeea

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *anthony
      - *bkp1
      - *master-04
      - *e39
  - path_regex: (nixos)/.*\.sops\.ya?ml
    key_groups:
    - age:
      - *anthony
      - *bkp1
      - *master-04
      - *e39
