---
keys:
  # Users
  - &anthony age12t69fa3kqmnxdx4sca7ecv6lfu3wrfwm95zuuhujcfk3ukcn8dzsk40u6x
  # Hosts
  - &bkp1 age1uvm732gdzuq2v2m97tw5gxerztw6ad3452xrpq5y9ggvg62x7fqse4pzly
  - &lga-test1 age1td7hkcms0fmrt438ta2kmxxfmp0lget6gdae7me60apprll543sqr525jy
  - &e39 age1a4uumamqg8248ntjjl088ppq7m75p6zyhu5r8yyaqjvvk5yjpuksqspeea
  - &octo age1kts52cy9j5cw3m9un0jy50kp9w7dqmshk0mrfysezxtae9nykvfq8wvuym

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *anthony
      - *bkp1
      - *lga-test1
      - *e39
      - *octo
