# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"
[asusctl]
src.git = "https://gitlab.com/asus-linux/asusctl.git"
fetch.git = "https://gitlab.com/asus-linux/asusctl.git"
cargo_lock = "Cargo.lock"
[supergfxctl]
src.git = "https://gitlab.com/asus-linux/supergfxctl.git"
fetch.git = "https://gitlab.com/asus-linux/supergfxctl.git"
cargo_lock = "Cargo.lock"
