# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  asusctl = {
    pname = "asusctl";
    version = "b6934bbf63ee57b0b9f38fdcf0da3dffeaca0928";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/asusctl.git";
      rev = "b6934bbf63ee57b0b9f38fdcf0da3dffeaca0928";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0qy9b5cmhjj500aw6j7ayh1q4qnv4bfmk8y0wqfx6wpcldpdj3xh";
    };
    cargoLock = {
      lockFile = ./asusctl-b6934bbf63ee57b0b9f38fdcf0da3dffeaca0928/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
  };
  supergfxctl = {
    pname = "supergfxctl";
    version = "7eabe91507764927768d2f48bac78b03fa8c77a9";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/supergfxctl.git";
      rev = "7eabe91507764927768d2f48bac78b03fa8c77a9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0bfafq15qqkk2im7ai2lqy55zn9lrqfws5kwmfsawiiz56qi9b0j";
    };
    cargoLock = {
      lockFile = ./supergfxctl-7eabe91507764927768d2f48bac78b03fa8c77a9/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
}
