---
name: NixOS

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v17

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: snowflake
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS config ❄️"
        run: |
          # This is a gross hack, but I can't figure out a nicer way
          # If I end up continue using this the pattern should be re-worked.
          # It's hardcore tech debt that will likely bite me soon :)
          sed -i '/work/d' flake.nix
          rm flake.lock
          # End glue
          nix build .#nixosConfigurations.rs2.system.build.toplevel
