name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - uses: nix-community/cache-nix-action@ac3050e3e4eb82fd7f7cc7c4cd944d89566e26fc # v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: snowflake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: nixbuild/nixbuild-action@4d83d2224e2b8a6eb6ddfd1b2525b1533d3f8bd1 # v20
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_AUTH_TOKEN }}
          generate_summary_for: 'workflow'
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@a2bbe0274e3a0c4194390a1e445f734c597ebc37 # v24
        with:
          pr-title: "chore(deps): update flake.lock"
          pr-labels: |
            dependencies
            automated