name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
      - uses: cachix/cachix-action@v15
        with:
          name: snowflake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: nixbuild/nixbuild-action@v20
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_AUTH_TOKEN }}
          generate_summary_for: 'workflow'
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "chore(deps): update flake.lock"
          pr-labels: |
            dependencies
            automated