anthonyjrabbito: ENC[AES256_GCM,data:h6JFOYm3MAXsQvFA,iv:Ka9RCCHr/jcwye45kwhtHDYMn3EvlUpbugTLxl+AzU4=,tag:tn/gP55p5B5Xs7eOKTlYLQ==,type:str]
root: ENC[AES256_GCM,data:stwuqOB4g4PC2M4kzw==,iv:G0HrNUQSEf3ZC5dmaLs4CaQrf+yoh918+eXgw531tRo=,tag:xoPqL9/rFnvjIMHzCR/slg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m4xc52pz2l2jpdqr5nslyj63aq90t62ywyv8te56wf7c2u7y3shs0avjud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaUlTSW9WL1l2MG8wWGt4
            K3dYVXI4WE1YZzdoQzJtS2FWbnVTc05rUDFBCkNJcGpCYTdjR1A3ZTNZOFJnSE90
            WXJ5V1NtdThZUG5GckUwUGtScHpudFkKLS0tIEQ2a0o5Sm1BN0VJU0hWbFFnTXNm
            aktFN0lrQTIxajE0UGI4TXVsc3BRQTgKm4vXTgYZQ4n4UQ8K+AZxlT4vUyJLZlBF
            ncpWemI3u+o+VLSNlXYFW9n/nSm2YtEkd0dBFXYf2ONyNh1h0jvmMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-12T22:55:56Z"
    mac: ENC[AES256_GCM,data:V6L3CsuBOT6KiW+d3Hvztez70d+e/Ici7f3ssm07J+HuXLbhLnrsoWaJEzB3WOoEksiBib03A8CD3eWFlcWqI3xPSyKHtSD1OEV8lKAt7PTVsEWH6p+8R+3kIcAPlQdzstA353jdZbtEnq8PZK4NvkJR0nUCPU2aV1ga1F6AUAs=,iv:XF+H6IN0+IWMm/ODVn3AlLSiVatyKaAaPucIsofTCRI=,tag:fzcJcbr19+WR4v1hvnvstw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
